### ISSUE TITLE
ZIP64 extensions

### ISSUE THREAD

**Issue by PsoAE** [gaow/SEQLinkage#12]
Hi,

I tried Seqlinkage a couple of weeks ago, but I cannot solve the problem with the Zip64 extensions.

I used this command:

seqlink --vcf input_vcf/EoE_exomes.QC_out.fixed_header.shortIDs.vcf.gz --fam input_vcf/EoE_exomes.fam --chrom-prefix chr --prevalence 0.0005 --moi AD --wt-pen 0.001 --mut-pen 0.8

The program is running, producing a cache directory with subdirectories containing LOC and PRE files per gene and pedigree. However, the program stops with an error message and no HTML file or heatmap is created.

Here is the stdout from the terminal:

MESSAGE: Binary trait detected in [/home/seqx/data/input_vcf/EoE_exomes.fam]
MESSAGE: Checking local resources 5/5 ...                                   
MESSAGE: 30 samples found in [/home/seqx/data/input_vcf/EoE_exomes.QC_out.fixed_header.shortIDs.vcf.gz]
MESSAGE: 4 families with a total of 30 samples will be scanned for 25,305 pre-defined units
MESSAGE: 14,743 units (from 60,289 variants) processed; 2,774 Mendelian inconsistencies and 7,648 recombination events handled
MESSAGE: 10,265 units ignored due to absence in VCF file
MESSAGE: 297 units ignored due to absence of variation in samples
MESSAGE: Archiving regional marker data to directory [/home/seqx/data/cache]
MESSAGE: 14,743 units will be converted to LINKAGE format
MESSAGE: 14,743 units successfully converted to LINKAGE format
MESSAGE: 19484 region - family pairs skipped
MESSAGE: Archiving LINKAGE format to directory [/home/seqx/data/cache]
Traceback (most recent call last):
  File "/opt/miniconda3/envs/snake/bin/seqlink", line 4, in <module>
    __import__('pkg_resources').run_script('SEQLinkage==1.0.0', 'seqlink')
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1490, in run_script
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/EGG-INFO/scripts/seqlink", line 103, in <module>
    
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Core.py", line 690, in main
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Utils.py", line 584, in write
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Utils.py", line 351, in zipdir
  File "/opt/miniconda3/envs/snake/lib/python2.7/zipfile.py", line 1148, in write
    self._writecheck(zinfo)
  File "/opt/miniconda3/envs/snake/lib/python2.7/zipfile.py", line 1114, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Files count would require ZIP64 extensions

Can I change anything in my command or is it an issue with the software/code?
Thanks for any help in advance!

**Comment by gaow** [comment]
Discussed in #10
