### ISSUE TITLE
ValueError: VCF line 1:897564 does not have valid allele frequency field ExAC.r0.3.1.sites.vep.vcf.gz

### ISSUE THREAD

**Issue by oleraj** [gaow/SEQLinkage#13]
Hi,

I'm trying to use SEQLinkage (v.1.0) with a frequency file and I'm getting an error message:
```
seqlink --fam masto_up.ped --vcf masto_up.filt.recode.vcf.gz --freq ExAC.r0.3.1.sites.vep.vcf.gz -f MERLIN
WARNING: Bind file source does not exist on host: /etc/resolv.conf
/opt/miniconda3/envs/snake/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
MESSAGE: Binary trait detected in [/spin1/users/oleraj/linkage/masto_up.ped]
MESSAGE: Checking local resources 5/5 ...                                   
MESSAGE: 24 samples found in [/spin1/users/oleraj/linkage/masto_up.filt.recode.vcf.gz]
MESSAGE: 6 samples found in FAM file but not in VCF file:
dad
CCGO_801139
CCGO_801142
CCGO_801143
mom
dad1
MESSAGE: 7 families with a total of 24 samples will be scanned for 25,305 pre-defined units
Process EncoderWorker-1:
Process EncoderWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/miniconda3/envs/snake/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/opt/miniconda3/envs/snake/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Core.py", line 537, in run
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Core.py", line 537, in run
    status = m.apply(self.data)
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Core.py", line 156, in apply
    format(self.vcf.GetChrom(), self.vcf.GetPosition(), self.af_info))
    status = m.apply(self.data)
  File "/opt/miniconda3/envs/snake/lib/python2.7/site-packages/SEQLinkage-1.0.0-py2.7.egg/SEQLinkage/Core.py", line 156, in apply
ValueError: VCF line 1:881627 does not have valid allele frequency field ExAC.r0.3.1.sites.vep.vcf.gz!
    format(self.vcf.GetChrom(), self.vcf.GetPosition(), self.af_info))
ValueError: VCF line 1:897564 does not have valid allele frequency field ExAC.r0.3.1.sites.vep.vcf.gz!
MESSAGE: 0 units (from 0 variants) processed; 0 Mendelian inconsistencies and 0 recombination events handled
MESSAGE: 18 units ignored due to absence in VCF file
MESSAGE: Archiving regional marker data to directory [/spin1/users/oleraj/linkage/cache]
MESSAGE: 0 units will be converted to MERLIN format
MESSAGE: 0 units successfully converted to MERLIN format
MESSAGE: Archiving MERLIN format to directory [/spin1/users/oleraj/linkage/cache]
MESSAGE: Saving data to [/spin1/users/oleraj/linkage/LINKAGE]
Traceback (most recent call last):
  File "/opt/miniconda3/envs/snake/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe
```

However, position 1:881627 looks fine to me in the ExAC VCF file I"m using for allele frequency:
```
1	881627	rs2272757	G	A	76830154.99	PASS	AC=68442;AC_AFR=1436;AC_AMR=5557;AC_Adj=68060;AC_EAS=5642;AC_FIN=4075;AC_Het=27348;AC_Hom=20356;AC_NFE=41521;AC_OTH=514;AC_SAS=9315;AF=0.564;AN=121382;AN_AFR=10282;AN_AMR=11482;AN_Adj=120386;AN_EAS=8600;AN_FIN=6550;AN_NFE=66084;AN_OTH=896;AN_SAS=16492;BaseQRankSum=-1.180e+00;ClippingRankSum=-3.070e-01;DB;DP=2706727;FS=0.000;GQ_MEAN=327.75;GQ_STDDEV=325.37;Het_AFR=1230;Het_AMR=2845;Het_EAS=1950;Het_FIN=1555;Het_NFE=15515;Het_OTH=214;Het_SAS=4039;Hom_AFR=103;Hom_AMR=1356;Hom_EAS=1846;Hom_FIN=1260;Hom_NFE=13003;Hom_OTH=150;Hom_SAS=2638;InbreedingCoeff=0.0825;MQ=59.38;MQ0=0;MQRankSum=0.055;NCC=120;POSITIVE_TRAIN_SITE;QD=22.39;ReadPosRankSum=0.289;VQSLOD=3.56;culprit=FS;DP_HIST=60|263|454|898|4730|6656|7035|7299|7216|6335|5327|4222|3004|2123|1466|945|629|412|289|1328,14|146|315|742|1709|3138|4601|5895|6434|5892|5109|4072|2900|2058|1407|918|614|401|283|1303;GQ_HIST=83|80|43|82|280|128|169|174|168|225|300|240|4912|2343|1302|1573|1434|918|1252|44985,13|30|26|53|79|49|80|93|97|150|221|175|334|428|304|551|652|466|801|43349;DOUBLETON_DIST=.;AC_MALE=38661;AC_FEMALE=29399;AN_MALE=66962;AN_FEMALE=53424;AC_CONSANGUINEOUS=1256;AN_CONSANGUINEOUS=2160;Hom_CONSANGUINEOUS=382;CSQ=A|upstream_gene_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000496938|processed_transcript||||||||||rs2272757&COSM1344685|1|685|-1|SNV|1|HGNC|24517||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000342066|protein_coding||||||||||rs2272757&COSM1344685|1|1672|1|SNV|1|HGNC|28706|YES||CCDS2.2|ENSP00000342313|SAM11_HUMAN|Q5SV95_HUMAN&I7FV93_HUMAN&A6PWC8_HUMAN|UPI0000D61E04|||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|synonymous_variant|LOW|NOC2L|ENSG00000188976|Transcript|ENST00000327044|protein_coding|16/19||ENST00000327044.6:c.1843C>T|ENST00000327044.6:c.1843C>T(p.%3D)|1893|1843|615|L|Ctg/Ttg|rs2272757&COSM1344685|1||-1|SNV|1|HGNC|24517|YES||CCDS3.1|ENSP00000317992|NOC2L_HUMAN||UPI000041820C|||hmmpanther:PTHR12687:SF4&hmmpanther:PTHR12687&Pfam_domain:PF03715&Superfamily_domains:SSF48371||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000464948|retained_intron||||||||||rs2272757&COSM1344685|1|3355|1|SNV|1|HGNC|28706||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000466827|retained_intron||||||||||rs2272757&COSM1344685|1|3445|1|SNV|1|HGNC|28706||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000474461|retained_intron||||||||||rs2272757&COSM1344685|1|3253|1|SNV|1|HGNC|28706||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000455979|protein_coding||||||||||rs2272757&COSM1344685|1|1988|1|SNV|1|HGNC|28706||||ENSP00000412228|||UPI000155D479|||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000483767|retained_intron|2/5||ENST00000483767.1:n.699C>T||699|||||rs2272757&COSM1344685|1||-1|SNV|1|HGNC|24517||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000478729|processed_transcript||||||||||rs2272757&COSM1344685|1|4074|1|SNV|1|HGNC|28706||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000477976|retained_intron|14/17||ENST00000477976.1:n.3290C>T||3290|||||rs2272757&COSM1344685|1||-1|SNV|1|HGNC|24517||||||||||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000341065|protein_coding||||||||||rs2272757&COSM1344685|1|1672|1|SNV|1|HGNC|28706||||ENSP00000349216|||UPI000155D47A|||||A:0.4419|A:0.0643|A:0.438||A:0.624|A:0.6332|A:0.5706|A:0.1562|A:0.6379||0&1|0&1||||||||||AGG|G;AC_POPMAX=5642;AN_POPMAX=8600;POPMAX=EAS;K1_RUN=G:3;K2_RUN=GG:1;K3_RUN=GGG:0;ESP_AF_POPMAX=0.6379069685935974;ESP_AF_GLOBAL=0.4747769832611084;ESP_AC=6174;KG_AF_POPMAX=0.6331999897956848;KG_AF_GLOBAL=0.44189298152923584;KG_AC=2213
```
The `AF` field is present as `AF=0.564;`.  Any idea why the code is throwing this error?

Thanks,

Andrew

**Comment by oleraj** [comment]
Never mind, I misunderstood the documentation.  the `--freq` option requires the TAG from the INFO field to use as for allele frequency information, not an additional VCF file.
