### ISSUE TITLE
issues with seqlinkage installation

### ISSUE THREAD

**Issue by valecipriani** [gaow/SEQLinkage#22]
Hi  I am using Ubuntu for Windows 10. 
I believe I correctly run the command: 
docker pull gaow/seqlink

If I run: docker images
I obtain:
REPOSITORY     TAG       IMAGE ID       CREATED        SIZE
gaow/seqlink   latest    e4fdb25d85ab   9 months ago   2.66GB

Now, when I run: seqlink -h 
I get the following: 
------------------------

Traceback (most recent call last):
  File "/opt/miniconda2/bin/seqlink", line 4, in <module>
    __import__('pkg_resources').run_script('SEQLinkage==1.1.0', 'seqlink')
  File "/opt/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/miniconda2/lib/python2.7/site-packages/SEQLinkage-1.1.0-py2.7.egg/EGG-INFO/scripts/seqlink", line 9, in <module>

  File "build/bdist.linux-x86_64/egg/SEQLinkage/Core.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/faulthandler.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/faulthandler.py", line 4, in __bootstrap__
  File "/opt/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1145, in resource_filename
    self, resource_name
  File "/opt/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1743, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "/opt/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1806, in _extract_resource
    manager.extraction_error()
  File "/opt/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1192, in extraction_error
    raise err
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s)
to the Python egg cache:

  [Errno 2] No such file or directory: '/tmp/Python-Eggs'

The Python egg cache directory is currently set to:

  /tmp/Python-Eggs

Perhaps your account does not have write access to this directory?
You can change the cache directory by setting the PYTHON_EGG_CACHE
environment variable to point to an accessible directory.
------------------------

I am not sure whether is a problem of simply updating PYTHON_EGG_CACHE (I tried but not successfully) 
or another rather a python issue. 

Any ideas please? 
Many thanks

**Comment by gaow** [comment]
@valecipriani could you confirm that there is this switch `-v /tmp:/tmp` in the `alias` you specified? What if you add to it: `-v /tmp/PYTHON_EGG_CACHE:/tmp/PYTHON_EGG_CACHE`, and try on your Ubuntu WSL, `mkdir -p /tmp/PYTHON_EGG_CACHE`, then run the command -- does it help? Please remember to load the bash configuration after you modify it to activate the change.

**Comment by valecipriani** [comment]
Fantastic. It works. I should have asked you much earlier instead of wasting hours. Thanks! 
vcipriani@DESKTOP-UI2KNDV:~$ seqlink -h
usage: seqlink [--bin FLOAT] [-b FILE] [--single-markers] --fam FILE --vcf
               FILE [--build STRING] [--freq INFO] [--freq_by_fam INFO]
               [--mle] [--rvhaplo] [--recomb_max INT] [--recomb_cross_fam]
               [--include_vars FILE] [-c P] [--chrom-prefix STRING] [-o Name]
               [-f FORMAT [FORMAT ...]] [-K FLOAT] [--moi STRING] [-W FLOAT]
               [-M FLOAT] [--theta-max FLOAT] [--theta-inc FLOAT]
               [--run-linkage] [--output-entries N] [-h] [-j N]
               [--tempdir PATH] [--cache] [-q]

        SEQLinkage, linkage analysis using sequence data
        [1.1.0]

Collapsed haplotype pattern method arguments:
  --bin FLOAT           Defines theme to collapse variants. Set to 0 for
                        "complete collapsing", 1 for "no collapsing", r2 value
                        between 0 and 1 for "LD based collapsing" and other
                        integer values for customized collapsing bin sizes.
                        Default to 0.8 (variants having r2 >= 0.8 will be
                        collapsed).
  -b FILE, --blueprint FILE
                        Blueprint file that defines regional marker (format:
                        "chr startpos endpos name avg.distance male.distance
                        female.distance").
  --single-markers      Use single variant markers. This switch will overwrite
                        "--bin" and "--blueprint" arguments.

Input / output options:
  --fam FILE            Input pedigree and phenotype information in FAM
                        format.
  --vcf FILE            Input VCF file, bgzipped.
  --build STRING        Reference genome version for VCF file.
  --freq INFO           Info field name for allele frequency in VCF file.
  --freq_by_fam INFO    Per family info field name for allele frequency in VCF
                        file.
  --mle                 Estimate allele frequency using MERLIN's MLE method.
  --rvhaplo             Only using rare variants for haplotyping
  --recomb_max INT      Maximum recombination events allowed per region.
  --recomb_cross_fam    Code sub-regions with cross family recombination
                        events; otherwise sub-regions are generated on per
                        family basis.
  --include_vars FILE   Variants to be included in CHP construction
  -c P, --maf-cutoff P  MAF cutoff to define "common" variants to be excluded
                        from analyses.
  --chrom-prefix STRING
                        Prefix to chromosome name in VCF file if applicable,
                        e.g. "chr".
  -o Name, --output Name
                        Output name prefix.
  -f FORMAT [FORMAT ...], --format FORMAT [FORMAT ...]
                        Output format. Default to LINKAGE.

LINKAGE options:
  -K FLOAT, --prevalence FLOAT
                        Disease prevalence.
  --moi STRING          Mode of inheritance, AD/AR: autosomal
                        dominant/recessive.
  -W FLOAT, --wt-pen FLOAT
                        Penetrance for wild type.
  -M FLOAT, --mut-pen FLOAT
                        Penetrance for mutation.
  --theta-max FLOAT     Theta upper bound. Default to 0.5.
  --theta-inc FLOAT     Theta increment. Default to 0.05.
  --run-linkage         Perform Linkage analysis using FASTLINK program.
  --output-entries N    Write the highest N LOD/HLOD scores to output tables.
                        Default to 10.

Runtime arguments:
  -h, --help            Show help message and exit.
  -j N, --jobs N        Number of CPUs to use.
  --tempdir PATH        Temporary directory to use.
  --cache               Load cache data for analysis instead of starting from
                        scratch.
  -q, --quiet           Disable the display of runtime MESSAGE.

        Copyright (c) 2013 - 2014 Gao Wang <wang.gao@columbia.edu>
        Distributed under GNU General Public License
        Home page: http://bioinformatics.org/seqlink


I can try use the software now. Hopefully I will not encounter any other issues! :-)
