### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by NElight** [gaow/SEQLinkage#46]
when i run seqlink, i get index out of range error.  it occur when only one variant in some range.
![image](https://user-images.githubusercontent.com/18420368/185012368-82bc8aa2-4572-48ce-ad1b-de138d3a02b9.png)

**Comment by gaow** [comment]
@NElight we are working on a new release with @changebio which should be out within 30 days. Do you have a small toy test data you can share (or email to me privately ) so we make sure our new release works without issue on your test data?

**Comment by NElight** [comment]
@gaow
[test.zip](https://github.com/gaow/SEQLinkage/files/9379300/test.zip)
this my test vcf file and fam file.

**Comment by NElight** [comment]
@gaow it is my test vcf file and fam file.
command is "seqlink --fam 3312362.fam --vcf last.vcf.gz --freq gnomAD_genome_AF --build hg19 -o LinkageAnalysis -K 0.0001 --moi AD -W 0 -M 1 -j 0 --run-linkage --debug"
[test.zip](https://github.com/gaow/SEQLinkage/files/9379304/test.zip)

**Comment by NElight** [comment]
@gaow Any new information about the test data?thank u.

**Comment by changebio** [comment]
Hi @NElight @gaow  Thank you for your patience. I just released our new version SEQLinkage v2. I have tested your data by the following command line `seqlink --fam test/3312362.fam --vcf test/last.vcf.gz --freq gnomAD_genome_AF --blueprint data/genemap.hg19.txt -o LinkageAnalysis -K 0.0001 --moi AD -W 0 -M 1 --chp --run-linkage`. You can follow the documentation (https://changebio.github.io/SEQLinkage/) to install and use SEQLinkage v2. Please let me know if you have any questions.

**Comment by gaow** [comment]
Thanks @changebio great I just saw this. Looks like it works. @NElight we have not yet built a docker image for that release, but @changebio has bumped it to Python 3 and streamlined the dependencies, so it should be easy to install using standard pip/conda commands. Still please let us know if there is an issue.

**Comment by NElight** [comment]
@gaow @changebio thank u very much

**Comment by NElight** [comment]
@changebio thank u , i rerun my test data using the new version SEQLinkage v2，get some ValueError.
![image](https://user-images.githubusercontent.com/18420368/187345333-e64116eb-f0dc-45ec-ad51-30bd5487ff5e.png)

**Comment by NElight** [comment]
@changebio thank u , i rerun my test data using the new version SEQLinkage v2，get another error.
![image](https://user-images.githubusercontent.com/18420368/187881172-6fe4a0ab-81c2-47c6-8bdd-b0ad66140fc8.png)

**Comment by changebio** [comment]
Could you send me more details. I cannot repeat your error. Did you get the error form CHP markers and/or single markers? Please show the command you used in the screenshot. @NElight

**Comment by NElight** [comment]
@changebio i am sorry for my incomplete information. i run the commands that you recommended, that two commands get the same error.
`seqlink --fam 3312362.fam --vcf last.vcf.gz --freq gnomAD_genome_AF -o LinkageAnalysis -K 0.0001 --moi AD -W 0 -M 1 --run-linkage --blueprint ~/.SEQLinkage/genemap.hg19.txt
MESSAGE: Binary trait detected in [/root/soft/test2/3312362.fam]
MESSAGE: Namespace(single_marker=False, tfam='/root/soft/test2/3312362.fam', vcf='/root/soft/test2/last.vcf.gz', anno=None, pop=None, included_vars=None, blueprint='/root/.SEQLinkage/genemap.hg19.txt', maf_cutoff=None, output='LinkageAnalysis', build='hg38', window=1000, freq='gnomAD_genome_AF', chr_prefix=None, run_linkage=True, prevalence=0.0001, inherit_mode='AD', wild_pen=0.0, muta_pen=1.0, theta_max=0.5, theta_inc=0.05)
MESSAGE: 8 samples found in [/root/soft/test2/last.vcf.gz]
MESSAGE: Loading marker map from [/root/.SEQLinkage/genemap.hg19.txt] ...
MESSAGE: 1 families with a total of 8 samples will be scanned for 28,488 pre-defined units
MESSAGE: VCF line 22:16150814 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16150827 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16229148 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16229290 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256512 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256578 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256800 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256822 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16264166 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16267115 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16278057 does not have valid allele frequency field gnomAD_genome_AF!
SNVHap OR11H1
SNVHap CCT8L2
MESSAGE: VCF line 22:17125797 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:17125814 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:17125899 does not have valid allele frequency field gnomAD_genome_AF!
SNVHap ANKRD62P1-PARP4P3
SNVHap HSFY1P1
SNVHap TMEM121B
SNVHap LINC01664
MESSAGE: VCF line 22:17687751 does not have valid allele frequency field gnomAD_genome_AF!
Family: 3312362 - Founders: 3  - Descendants: 5  - Bits: 7 
  Skipping Marker rs150003389 [BAD INHERITANCE]

MESSAGE: VCF line 22:18031778 does not have valid allele frequency field gnomAD_genome_AF!
Family: 3312362 - Founders: 3  - Descendants: 5  - Bits: 7 
  Skipping Marker rs5747148  [BAD INHERITANCE]
  Skipping Marker rs5992061  [BAD INHERITANCE]

MESSAGE: VCF line 22:18080755 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18640563 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18653419 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18766123 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18766290 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18769261 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775399 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775403 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775424 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775482 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778603 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778675 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778789 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778811 does not have valid allele frequency field gnomAD_genome_AF!
SNVHap GGT3P
MESSAGE: VCF line 22:18842088 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842200 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842353 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842901 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844558 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844654 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844763 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844942 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845064 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845939 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845990 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845998 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846187 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846228 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846232 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846236 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18897985 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18909586 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18910563 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18909586 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18910563 does not have valid allele frequency field gnomAD_genome_AF!
SNVHap DGCR5
MESSAGE: write to pickle: LinkageAnalysis/chrallresult/chrallresult0.pickle,Gene number:25,Time:0.0005413910116638161
create LinkageAnalysis/chrallresult/chrallresult0_AFcutoffNone_linkage.input
create LinkageAnalysis/chrallresult/chrallresult0_AFcutoffNone_linkage.lods
0.26902893278747797
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 220, in calculate_ped_lod
    tmp = _calculate_ped_lod(mped, aff = aff, model = modAD,rho=r)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 208, in _calculate_ped_lod
    res.MARKER=list(ped.columns[6:])[::2]
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/generic.py", line 5604, in __setattr__
    self[name] = value
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/frame.py", line 3655, in __setitem__
    self._set_item(key, value)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/frame.py", line 3832, in _set_item
    value = self._sanitize_column(value)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/frame.py", line 4535, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (27) does not match length of index (1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/conda/envs/seqlinkv2/bin/seqlink", line 8, in <module>
    sys.exit(main())
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Main.py", line 131, in main
    run_each_region(regions,data,RegionExtractor(args.vcf, build = args.build, chr_prefix = args.chr_prefix),MarkerMaker(maf_cutoff = args.maf_cutoff),LinkageWriter(len(samples_not_vcf)),
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Core.py", line 793, in run_each_region
    linkage_analysis(gene_genotype_file,data.fam,data.fam_vcf,cutoff,chp,rho,model,chrom,penetrances,dfreq)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 276, in linkage_analysis
    res = parallel_lods(gene_fam_haps,afreqs,rho,model,chrom,penetrances,dfreq) #R function for linkage analysis
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 239, in parallel_lods
    return {k:res for k,res in zip(haps.keys(),results)}
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 239, in <dictcomp>
    return {k:res for k,res in zip(haps.keys(),results)}
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ValueError: Length of values (27) does not match length of index (1)
R[write to console]: There were 25 warnings (use warnings() to see them)
R[write to console]: 

`
`seqlink --fam 3312362.fam --vcf last.vcf.gz --freq gnomAD_genome_AF -o LinkageAnalysis -K 0.0001 --moi AD -W 0 -M 1 --run-linkage --blueprint ~/.SEQLinkage/genemap.hg19.txt --single-marker
MESSAGE: Binary trait detected in [/root/soft/test2/3312362.fam]
MESSAGE: Namespace(single_marker=True, tfam='/root/soft/test2/3312362.fam', vcf='/root/soft/test2/last.vcf.gz', anno=None, pop=None, included_vars=None, blueprint='/root/.SEQLinkage/genemap.hg19.txt', maf_cutoff=None, output='LinkageAnalysis', build='hg38', window=1000, freq='gnomAD_genome_AF', chr_prefix=None, run_linkage=True, prevalence=0.0001, inherit_mode='AD', wild_pen=0.0, muta_pen=1.0, theta_max=0.5, theta_inc=0.05)
MESSAGE: 8 samples found in [/root/soft/test2/last.vcf.gz]
MESSAGE: Loading marker map from [/root/.SEQLinkage/genemap.hg19.txt] ...
MESSAGE: 1 families with a total of 8 samples will be scanned for 28,488 pre-defined units
MESSAGE: VCF line 22:16150814 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16150827 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16229148 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16229290 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256512 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256578 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256800 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16256822 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16264166 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16267115 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:16278057 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:17125797 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:17125814 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:17125899 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:17687751 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18031778 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18080755 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18640563 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18653419 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18766123 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18766290 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18769261 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775399 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775403 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775424 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18775482 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778603 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778675 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778789 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18778811 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842088 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842200 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842353 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18842901 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844558 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844654 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844763 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18844942 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845064 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845939 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845990 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18845998 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846187 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846228 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846232 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18846236 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18897985 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18909586 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: VCF line 22:18910563 does not have valid allele frequency field gnomAD_genome_AF!
MESSAGE: write to pickle: LinkageAnalysis/chrallresult/chrallresult0.pickle,Gene number:25,Time:4.5880510264800656e-05
exist! jump LinkageAnalysis/chrallresult/chrallresult0_AFcutoffNone_linkage.input
create LinkageAnalysis/chrallresult/chrallresult0_AFcutoffNone_linkage.lods
0.2794072828255594
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 220, in calculate_ped_lod
    tmp = _calculate_ped_lod(mped, aff = aff, model = modAD,rho=r)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 208, in _calculate_ped_lod
    res.MARKER=list(ped.columns[6:])[::2]
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/generic.py", line 5604, in __setattr__
    self[name] = value
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/frame.py", line 3655, in __setitem__
    self._set_item(key, value)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/frame.py", line 3832, in _set_item
    value = self._sanitize_column(value)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/frame.py", line 4535, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/pandas/core/common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (27) does not match length of index (1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/conda/envs/seqlinkv2/bin/seqlink", line 8, in <module>
    sys.exit(main())
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Main.py", line 131, in main
    run_each_region(regions,data,RegionExtractor(args.vcf, build = args.build, chr_prefix = args.chr_prefix),MarkerMaker(maf_cutoff = args.maf_cutoff),LinkageWriter(len(samples_not_vcf)),
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Core.py", line 793, in run_each_region
    linkage_analysis(gene_genotype_file,data.fam,data.fam_vcf,cutoff,chp,rho,model,chrom,penetrances,dfreq)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 276, in linkage_analysis
    res = parallel_lods(gene_fam_haps,afreqs,rho,model,chrom,penetrances,dfreq) #R function for linkage analysis
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 239, in parallel_lods
    return {k:res for k,res in zip(haps.keys(),results)}
  File "/home/conda/envs/seqlinkv2/lib/python3.10/site-packages/SEQLinkage/Linkage.py", line 239, in <dictcomp>
    return {k:res for k,res in zip(haps.keys(),results)}
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/conda/envs/seqlinkv2/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ValueError: Length of values (27) does not match length of index (1)
R[write to console]: There were 25 warnings (use warnings() to see them)
R[write to console]: 

`

**Comment by NElight** [comment]
@changebio i am sorry for my incomplete information. i run the commands that you recommended, that two commands get the same error.
![2022-09-03_082908](https://user-images.githubusercontent.com/18420368/188248750-f9ec4ad9-9c78-4fd1-a4b0-7533905a372e.jpg)
